create table products (
    id bigint generated by default as identity,
    name varchar(255) not null,
    price numeric(10,2) precision not null,
    available_stock integer not null,
    primary key (id)
);

create table customers (
    id bigint generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null unique,
    primary key (id)
);

create table orders (
    id bigint generated by default as identity,
    order_status varchar(255) check (order_status in ('PENDING', 'PAID', 'REFUSED')) not null,
    customer_id bigint not null,
    primary key (id)
);

create table order_items (
    id bigint generated by default as identity,
    quantity integer not null,
    price numeric(10,2) not null,
    product_id bigint not null,
    order_id bigint not null,
    primary key (id)
);

alter table if exists orders
    add constraint fk_order_customer
    foreign key (customer_id)
    references customers;

alter table if exists order_items
    add constraint fk_order_item_product
    foreign key (product_id)
    references products;

alter table if exists order_items
    add constraint fk_order_item_order
    foreign key (order_id)
    references orders;