create table tb_users (
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) check ( role in ('ADMIN', 'CUSTOMER')) not null,
    primary key (id)
);

insert into users (email, password, role)
VALUES ('admin@loja.com', 'f7758199a85c36d8e796ca54b4e83974136f0c1d', 'ADMIN');